dist: trusty

language: php

env:
    global:
        - APP_ENV=test
        - MONOFONY_CACHE_DIR=$HOME/.monofony-cache
        - MONOFONY_BUILD_DIR=etc/build

matrix:
    include:
        -
            sudo: required
            php: 7.2
            env:
                - MONOFONY_SUITE="application"
                - TRAVIS_NODE_VERSION="7.5"
            services:
                - memcached
        -
            sudo: false
            php: 7.2
            env: MONOFONY_SUITE="docs packages"
            addons:
                apt:
                    packages:
                        - parallel

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files
        - ~/.cache/pip
        - vendor
        - node_modules
        - $MONOFONY_CACHE_DIR

before_install:
    - etc/travis/run-suite before_install "${MONOFONY_SUITE}"

install:
    - etc/travis/run-suite install "${MONOFONY_SUITE}"

before_script:
    - etc/travis/run-suite before_script "${MONOFONY_SUITE}"

script:
    - etc/travis/run-suite script "${MONOFONY_SUITE}"

before_cache:
    - etc/travis/run-suite before_cache "${MONOFONY_SUITE}"

after_success:
    - etc/travis/run-suite after_success "${MONOFONY_SUITE}"

after_failure:
    - etc/travis/run-suite after_failure "${MONOFONY_SUITE}"

after_script:
    - etc/travis/run-suite after_script "${MONOFONY_SUITE}"

notifications:
    email: false
