#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

print_header "Validating (Twig templates)" "Monofony"
run_command "bin/console lint:twig templates"
